version: "3"

services:
  team18_db:
    container_name: team18_db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-restaurant}
      POSTGRES_USER: ${POSTGRES_USER:-team18}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    networks:
      - team18_db
    restart: unless-stopped
  team18_db_test:
    container_name: team18_db_test
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST:-restaurant}
      POSTGRES_USER: ${POSTGRES_USER:-team18}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      PGDATA: /var/lib/postgresql/data_test
    volumes:
      - ./db/data_test:/var/lib/postgresql/data_test
      - ./db/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5433:5432"
    networks:
      - team18_db_test
    restart: unless-stopped
  team18_db_manager:
    container_name: team18_db_manager
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./db/db_manager:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - team18_db
      - team18_db_test
    networks:
      - team18_db
      - team18_db_test
    restart: unless-stopped
  team18_api:
    container_name: team18_api
    build:
      context: ./api
      dockerfile: Dockerfile.dev # on move to prod, update this
    volumes:
      - /api/node_modules
      - ./api:/api
    ports:
      - "3000:3000"
    depends_on:
      - team18_db
      - team18_db_test
    networks:
      - team18_db
      - team18_db_test
      - team18_app
    restart: unless-stopped
  team18_app:
    container_name: team18_app
    build:
      context: ./app
      dockerfile: Dockerfile.dev # on move to prod, update this
    volumes:
      - /app/node_modules
      - ./app:/app
    ports:
      - "8000:3000"
    networks:
      - team18_app
    restart: unless-stopped
networks:
  team18_app:
  team18_db:
    driver: bridge
  team18_db_test:
    driver: bridge
